- src/gcp_scanner/test_unit.py
> test: refactored crawler unittests (#14)

- src/gcp_scanner/crawl.py
> fix: wrong docstring for `get_gke_clusters` function

- src/gcp_scanner/credsdb.py
- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_unit.py
Fixes #21 
As I investigated, As of now, I found that `refresh_tokens` are bounded with scopes already.  So I think we don't need to enforce `cloud-platform` scope for `refresh_token`. However, we can use a refresh token to retrieve the access token with the scope list.
This solution uses the refresh token to retrieve the list of scopes.
I implemented some unit tests by mocking the API response.
As far as I read about unit testing. I think we should not depend on the test_project for unit tests. We can call those gcp-dependent tests **"Integration Test"**
I am not perfectly sure though as I don't have expert-level experience in these. Looking for your opinion here
> feat: OAuth2 credentials with no scopes for refresh token

- src/gcp_scanner/test_unit.py
- test/refresh_scopes
> test: added integration test boilerplate for get_refresh_token_scope

- README.md
docs: updated README.md with python-client version
To documentation be beginner friendly and to avoid confusion, I have made some contribution on README.md
As in the current README.md file its mentioned that, replace "google-api-python-client==2.9.0 with google-api-python-client==1.8.0 in pyproject.toml". But, in the ./pyproject.toml file it has given that version of google-api-python-client is 2.80.0 initially. So, I have just changed the version.
- [ x ] I have read and followed the contributing guidelines.
- [ x ] I have tested my changes thoroughly and they work as expected.
- [ x ] I have added necessary tests for the changes made.
- [ x ] I have updated the documentation to reflect the changes made.
- [ x ] My code follows the project's coding style and standards.
- [ x ] I have …
> docs: updated README.md with python-client version

- src/gcp_scanner/scanner.py
This PR fixes https://github.com/google/gcp_scanner/issues/79.
This PR is continuation of #84.
Reason of Bug
The current src/gcp_scanner/scanner.py file in the codebase, creates a JSON file with the name of the project to store the output of the scan. If the file already exists, it opens the same file in the append mode and appends the output of the scan to the same file.
Approach to fix the bug
I added the timestamp of the scan to the name of the output file while writing the scan results. In this way, for every scan, there will be different output files where the output would be written into.
Before the changes
The output gets appended to same file in case of multiple scans.
> fix: Add timestamp to filename while saving output of gcp scan

- example_config
- src/gcp_scanner/arguments.py
- src/gcp_scanner/crawl.py
- src/gcp_scanner/credsdb.py
- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_acceptance.py
- src/gcp_scanner/test_unit.py
- test/dns_policies
- test/services
- test/sourcerepos
- test/storage_buckets
We use a predefined schema to select the most interesting fields for printing. User can enable it with -ls flag.
* added new function to save results
* Requests are now timed out by 120 seconds
* Impersonation is now disabled by default
* Unwrapped several unnecessary lists in responses
* Fixes extra null output in GCS scanning results
#135
> feat: Enable lightweight scanning option

- src/gcp_scanner/client/__init__.py
- src/gcp_scanner/client/client_factory.py
- src/gcp_scanner/client/dns_client.py
- src/gcp_scanner/client/interface_client.py
- src/gcp_scanner/crawl.py
- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_unit.py
closes #155 
1. implemented client factory folder structure
2. implemented creation of DNSClient using factory
3. refactored `get_managed_zones` and `test_dns_policies` with DNSClient
4. updated unit test to call `get_managed_zones` and `test_dns_policies` with new method signature.
> refactor :hammer: : implement client factory for DNS client [#155]

- src/gcp_scanner/client/client_factory.py
- src/gcp_scanner/client/cloud_source_manager_client.py
- src/gcp_scanner/client/kms_client.py
- src/gcp_scanner/client/service_management_client.py
- src/gcp_scanner/client/sourcerepo_client.py
- src/gcp_scanner/crawl.py
- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_unit.py
closes #174 
closes #175 
closes #176 
closes #177
> feat: implement client factory for kms, service usage, sourcerepo, resource manager

- src/gcp_scanner/crawl.py
- src/gcp_scanner/crawler/__init__.py
- src/gcp_scanner/crawler/compute_disks_crawler.py
- src/gcp_scanner/crawler/compute_firewall_rules_crawler.py
- src/gcp_scanner/crawler/compute_images_crawler.py
- src/gcp_scanner/crawler/compute_instances_crawler.py
- src/gcp_scanner/crawler/compute_snapshots_crawler.py
- src/gcp_scanner/crawler/compute_static_ips_crawler.py
- src/gcp_scanner/crawler/compute_subnets_crawler.py
- src/gcp_scanner/crawler/crawler_factory.py
- src/gcp_scanner/crawler/interface_crawler.py
- src/gcp_scanner/crawler/machine_images_crawler.py
- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_unit.py
> feat :sparkles: compute crawler factories

- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_unit.py
closes #141 
- moved the logic of fetching sa_credentials to a method
- handled exception while fetching sa_credentials from keyfiles
- added error log for all the malformed keyfiles
> fix: handle bad keyfiles

- visualization_tool/src/types/resources.ts
This PR is for adding the initial structure of the resource to define its attributes after parsing files. 
Add new file `types/resources.ts`
> Adding initial Typescript types for resources

- src/gcp_scanner/crawl.py
- src/gcp_scanner/crawler/app_services_crawler.py
- src/gcp_scanner/crawler/bigquery_crawler.py
- src/gcp_scanner/crawler/bigtable_instances_crawler.py
- src/gcp_scanner/crawler/cloud_functions_crawler.py
- src/gcp_scanner/crawler/cloud_resource_manager_iam_policy_crawler.py
- src/gcp_scanner/crawler/cloud_resource_manager_project_info_crawler.py
- src/gcp_scanner/crawler/compute_disks_crawler.py
- src/gcp_scanner/crawler/compute_firewall_rules_crawler.py
- src/gcp_scanner/crawler/compute_images_crawler.py
- src/gcp_scanner/crawler/compute_instances_crawler.py
- src/gcp_scanner/crawler/compute_snapshots_crawler.py
- src/gcp_scanner/crawler/compute_static_ips_crawler.py
- src/gcp_scanner/crawler/compute_subnets_crawler.py
- src/gcp_scanner/crawler/dns_managed_zones_crawler.py
- src/gcp_scanner/crawler/dns_policies_crawler.py
- src/gcp_scanner/crawler/endpoints_crawler.py
- src/gcp_scanner/crawler/filestore_instances_crawler.py
- src/gcp_scanner/crawler/kms_keys_crawler.py
- src/gcp_scanner/crawler/machine_images_crawler.py
- src/gcp_scanner/crawler/misc_crawler.py
- src/gcp_scanner/crawler/pubsub_subscriptions_crawler.py
- src/gcp_scanner/crawler/service_accounts_crawler.py
- src/gcp_scanner/crawler/service_usage_crawler.py
- src/gcp_scanner/crawler/source_repo_crawler.py
- src/gcp_scanner/crawler/spanner_instances_crawler.py
- src/gcp_scanner/crawler/sql_instances_crawler.py
- src/gcp_scanner/scanner.py
- src/gcp_scanner/test_unit.py
closes #227 
related to #153 
I've created this PR to improve the way we express the idea. Most of the crawlers have already been implemented, but we still have a few more to go, specifically #229, #230, and #231.
However, we won't be able to completely remove the old crawl.py just yet. We need to have a discussion about the following points:
- Where should we put the remaining pieces of code from `crawl.py`?
- We couldn't include the **storage_bucket** and **gke** related crawler in the double loop method. Any ideas on how to handle that?
- the signature of the `project_list` crawler does not match with the interface, how to refactor this? 
Also, let's brainstorm ways to polish and enhance this draft.
mentions: @mshudrak @0xDeva @peb-peb and others.
> :recycle: refactor scanner.py to reduce repetative if statements.

- src/gcp_scanner/crawler/storage_buckets_crawler.py
In Python3 older than 3.10 we have the following error:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'.
This commit fixes this issue.
Fix #238
[Provide a brief description of the changes you have made and why they are necessary.]
> fix: Unsupported NoneType on Python older than 3.10

- MANIFEST.in
- pyproject.toml
Get rid of using the hatch system and instead use MANIFEST.in file which is compatible with setuptools system
- remove `hatch.build` section from `pyproject.toml` file
- add `MANIFEST.in` file to exclude test files
#186
> fix: use MANIFEST.in for controlling files in the distribution 

- src/gcp_scanner/scanner.py
The function is not being used anywhere in the code-base and is redundant.
It was removed in the PR #159 and is implemented in the `src/gcp_scanner/client/compute_client.py`
> remove: `compute_client_for_credentials` func from scanner

- src/gcp_scanner/crawler/storage_buckets_crawler.py
This PR fixes an inconsistency of exceptions handling in storage_buckets_crawler and the rest of crawlers.
In some cases, request can raise not HTTP related error which would stop GCP scanner execution.
[Provide a brief description of the changes you have made and why they are necessary.]
> Unify exception handler in storage_buckets_crawler

- src/gcp_scanner/arguments.py
- src/gcp_scanner/error_handler.py
Fixes the bug #271 where GCP Scanner freezes when there is an error in project scanning crawler.
We have solved this issue/bug by exiting the program if the output folder path is invalid. We verify the argument when it is passed by the user.
#271
:point_down: if the output folder path is invalid
:point_down: if the output folder path is valid
> fix: hanging bug if output folder doesn't exist

- requirements.txt
- src/gcp_scanner/gui/app.py
- visualization_tool/src/App.tsx
- visualization_tool/src/components/ControlMenu/ControlMenu.tsx
- visualization_tool/src/components/Navbar/Navbar.tsx
- visualization_tool/src/components/ResourcesList/utils.ts
- visualization_tool/src/main.tsx
- visualization_tool/tsconfig.json
- visualization_tool/vite.config.ts
Instead of adding `flask` to the project dependencies to create the server that hosts the tool, use the already existing Python `http.server` module for creating the server
- Change implementationon of `gui/app.py`
- Fix some errors related to building the visualization tool
- Remove `static` word from tool URLs
The following steps to build the tool and test it after the build
1. `cd visualization_tool/`
2. `npm run build`
3. `cd  cd ../src/gcp_scanner/gui/`
4. `python app.py`
> chore: Replace flask with http.server python module  for serving visualization tool

- visualization_tool/src/components/ResourcesList/ResourcesList.tsx
- visualization_tool/src/parser/parser.ts
- visualization_tool/src/types/resources.ts
Fix error `Invalid file` related to missing `iam_policy` key from the output of the GCP Scanner 
- Make the `iam_policy` field optional in the `OutputFile` type
- Edit the parser to check if the `iam_policy` field exists or not
- Add a fallback value to the `key` property in the `ResourcesList`
> fix: Handle of missing iam_policy key in input JSON

- src/gcp_scanner/crawler/app_services_crawler.py
- src/gcp_scanner/crawler/bigquery_crawler.py
- src/gcp_scanner/crawler/bigtable_instances_crawler.py
- src/gcp_scanner/crawler/cloud_functions_crawler.py
- src/gcp_scanner/crawler/cloud_resource_manager_project_list_crawler.py
- src/gcp_scanner/crawler/compute_disks_crawler.py
- src/gcp_scanner/crawler/compute_firewall_rules_crawler.py
- src/gcp_scanner/crawler/compute_images_crawler.py
- src/gcp_scanner/crawler/compute_instances_crawler.py
- src/gcp_scanner/crawler/compute_snapshots_crawler.py
- src/gcp_scanner/crawler/compute_static_ips_crawler.py
- src/gcp_scanner/crawler/compute_subnets_crawler.py
- src/gcp_scanner/crawler/dns_managed_zones_crawler.py
- src/gcp_scanner/crawler/endpoints_crawler.py
- src/gcp_scanner/crawler/filestore_instances_crawler.py
- src/gcp_scanner/crawler/machine_images_crawler.py
- src/gcp_scanner/crawler/pubsub_subscriptions_crawler.py
- src/gcp_scanner/crawler/service_accounts_crawler.py
- src/gcp_scanner/crawler/spanner_instances_crawler.py
- src/gcp_scanner/crawler/sql_instances_crawler.py
We had a bug in most of our crawlers when data would be replaced instead of appended to results list.
Fixes #254
> Use extend on crawlers to avoid replacing results

- .github/workflows/python-app.yml
This pull request addresses the previous slow execution time of our GitHub Actions workflow which was averaging around 2 minutes and 30 seconds. By caching dependencies and parallelizing the linting and testing jobs, this PR aims to significantly reduce the workflow execution time, thus speeding up our CI/CD pipeline.
- Added a step to cache Python dependencies using the `actions/cache` action.
- Split the 'Lint with pylint' and 'Test with pytest' steps into separate parallel jobs to allow for faster execution.
- These changes are expected to provide a notable improvement in the workflow execution time, making our development process more efficient.
> Optimize GitHub Actions Workflow: Cache Dependencies install and Parallelize Linting & Testing

- src/gcp_scanner/crawler/interface_crawler.py
- src/gcp_scanner/crawler/storage_buckets_crawler.py
- src/gcp_scanner/scanner.py
- Issue: https://github.com/google/gcp_scanner/issues/241. Hence I created a property `crawler_config` in base class `ICrawler` which is returns bool value, where `default=False`
- If there is a need or optionality of passing the config to the crawler then this property `crawler_config` in the base class needs to be overridden in the sub class to return True.
**Note** : Currently as I was checking all the crawlers, I have just seen that config is being used only inside the `StorageBucketsCrawler` crawler. So only its value is set as True in its base class.
- Base class `ICrawler` has a new property called as `crawler_config` which returns the abstracted private variable `_config_depndency` which is set to **False** by default.
- `StorageBucketsCrawler` class has overridden …
> Refinement: Removed Redundancy of Scan Config Passing

- INSTALL.md
Made a minor change to the command to activate virtual environment on windows in INSTALL.md
changed this  `.\venv\Scripts\activate.bat` to this `.\venv\Scripts\activate`
> Docs: Corrected command to activate virtual environment on windows.

- src/gcp_scanner/credsdb.py
- src/gcp_scanner/scanner.py
Fixing a bug when -p and -f specified together and project already exists in the original list.
1. Fixed -p/-f bug
2. Fixed printing (switched print to logging.info) on inspecting projects and impersonation
> Fixing -p/-f option and printing

- .github/workflows/python-app.yml
In one of the GitHub action there was a link present for documentation on using python with GitHub Actions but the link was redirecting to support page.
I found another similar documentation on docs page of GitHub Actions and this PR updates that link.
- Updated the docs link in GitHub action `python-app.yml`
> Fix broken link to docs page
