src/gcp_scanner/credsdb.py

I solved the problem by providing multiple formats of strptime and verifying them

fix ValueError #8

---

src/gcp_scanner/crawl.py
src/gcp_scanner/credsdb.py
src/gcp_scanner/scanner.py

Hey there,
this will close #17 
> **Warning**
> I have never run the code because I have not used the GCP. So please give it a good test!
I did my best to determine the loglevel. In some places it may be better to use a warning or even critical. Here I am however dependent on your help. 
But I think this should be enough for the beginning.
If the log output is a bit much, please sprinkle a little loglevel debug over it.
In order to not create pylint errors, I had to wrap some lines.
Although #16, I still used the string formatting. My understanding is that this is best practice in combination with logging:
- https://docs.python.org/3/howto/logging.html#optimization
- https://pylint.pycqa.org/en/latest/user_guide/messages/warning/logging-format-interpolation.html
- …

replaces all print functions

---

README.md

docs: fixed minor spelling and grammartical issues in the readme.md (#27)

---

src/gcp_scanner/scanner.py
test/sourcerepos

Added new test file for cloud source repo
Fixed small nit in the logging.

Add cloudsource repo test file and fix logging nit.

---

src/gcp_scanner/scanner.py

Type checking update for is_set() method

Type check is_set()

---

src/gcp_scanner/crawl.py

Eliminated nested for loops and replaced it with list comprehension.

Update crawl.py - for loops to list comprehension

---

CONTRIBUTING.md

Add commit and branching naming conventions to contributing.md
Improved CONTRIBUTING.md with naming conventions
#24 Include commit message and branch naming conventions in the contributing.md
I am looking forward to contributing to the GCP Scanner!

docs: add commit and branching naming conventions to contributing.md

---

CONTRIBUTING.md

Fixed CONTRIBUTING.md file Formatting Error
Added markdown text to highlight text as code and fix formatting error
https://github.com/google/gcp_scanner/issues/78 fomatting error in the contributing.md
Looking forward to contributing more to the project!

docs: fixed CONTRIBUTING.md formatting error

---

requirements.txt

fix: update packages to the latest version available
- update packages
no

fix: update packages to the latest version available

---

test/services

Fixing volatile test results for GCP Services API.
* update test/services
#6

Fix breaking services unit test

---

CONTRIBUTING.md

This pull request makes several updates to the CONTRIBUTING.md file to improve its readability, accuracy, and overall helpfulness. 
Specifically, I made the following changes:
- Fixed a spelling mistake in the document.
- Added missing information about getting help and the code of conduct.
- Reformatted the examples of commit messages and branching naming conventions to make them more visually appealing.
- Converted the contribution guidelines table into Markdown format for easier readability.
- Added links to the project documentation and contact information in the CONTRIBUTING.md file.
These changes should make it easier for new contributors to get started with the project and understand the guidelines for contributing.
This pull request resolves issue #24, which requested improvements …

docs: Update CONTRIBUTING.md file which closes #24

---

src/gcp_scanner/scanner.py

changed f-string logging implementation to lazy % formatting for logs
Issue #103 
The changes have been tested on my local machine for `pylint`.

FIX: fixes the incorrect logging

---

test/services

Modifying title of service to match GCP output.
* test/services

test: Fix failing services test

---

example_config
src/gcp_scanner/crawl.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py
test/machine_images

Added support for Machine Image Resources in the tool. 
Changes have been made in the following files:

✨ FEAT: Machine Images Resources 

---

src/gcp_scanner/test_acceptance.py
test/compute_instances
test/machine_images

Fixing volatile tests.
1. Fixing acceptance test
2. Fixing Compute Instances test
3. Fixing machine images test introduced in #111.
PR #111

Fixing scanner unit and acceptance tests

---

.github/workflows/release-please.yml
CONTRIBUTING.md

- Enable release-please-action
- #20

ci: Enable versioning

---

README.md

Added the version tag badge in the README.md
Fixes #124 

Add the version tag badge in the README.md

---

CONTRIBUTING.md
INSTALL.md

The above document would provide a detailed description to new contributors to setup `gcp_scanner` on their local environment. 
- added `INSTALL.md` docs for the installation guide on the tool.
- should we add any other points or links in this?
- like the pypi 
- I have added each code in triple ticks ``` (or codeblock) instead of a single tick ` as this enables the **copy** button.

📝 docs: INSTALL.md

---

INSTALL.md

There was no clear description for users which are operating on a Mac-based-machine. So I have added installation sections for those users.
Added sections for Creating a virtual environment and setting up that virtual environment on Mac.
#125 -->Here, the issue was raised first.
As there is just a change of shell from moving from linux to Mac--bash-->zsh.
The commands remain same as they are for linux.
Also was thinking if we could just add an OR inside the linux OR Mac--which could potentially save the lines of code, but would sacrifice clarity!

Installation Guide updatation for MacOS users.

---

src/gcp_scanner/crawl.py
src/gcp_scanner/scanner.py

* Added GCS root bucket name into the output of the full scan
* Added unique name generation for GCS files list output
Fixes #23 and #148.

Adding GCS bucket name in the output

---

src/gcp_scanner/client/bigtable_client.py
src/gcp_scanner/client/client_factory.py
src/gcp_scanner/client/cloud_functions_client.py
src/gcp_scanner/client/filestore_client.py
src/gcp_scanner/client/spanner_client.py
src/gcp_scanner/crawl.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py

closes #169 
closes #171 
closes #172 
closes #173

feat: implement client factory for cloud function, bigtable, spanner and filestore.

---

README.md

Add updated description where gcp scanner pulled with `pip install`

misc: update README.md to have new pip command

---

scanner.py
src/gcp_scanner/arguments.py
src/gcp_scanner/conftest.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_params.py

- added performance INFO in logs for the project using the `time` library's `perf_counter()` and `process_time()`.
- `perf_counter()` - measures the time since the program started
- `process_time()` - measures the time spent by the current process executing code
- **Results: (sample space = 10)**
- Average Elapsed time since the program started: **146.262744**
- Average Elapsed time spent by the current process executing code: **4.424605**
**NOTE:** [related docs for above topic](https://docs.python.org/3/library/time.html#time.perf_counter)
- `scanner.py` - added performance INFO in logs
The goal is to improve the "Average Elapsed time since the program started" time significantly.

⚡️ feat: add performance INFO in logs

---

example_config
src/gcp_scanner/crawl.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py
test/storage_buckets_iam

As part of my work assignment, I should collect all IAM permissions per bucket across GCP Organization. I added these features in this PR. 

Add support get_bucket_iam

---

src/gcp_scanner/crawl.py
src/gcp_scanner/crawler/bigtable_instances_crawler.py
src/gcp_scanner/crawler/crawler_factory.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py

closes #199 
ref to #153 
@mxmssh @ZetaTwo

refactor: Crawler/bigtable instances

---

src/gcp_scanner/crawl.py
src/gcp_scanner/crawler/crawler_factory.py
src/gcp_scanner/crawler/filestore_instances_crawler.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py

closes #201 
ref to #153
@mxmssh @ZetaTwo

refactor: Crawler/filestore instances

---

src/gcp_scanner/crawl.py
src/gcp_scanner/crawler/crawler_factory.py
src/gcp_scanner/crawler/sql_instances_crawler.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py

closes #205 
ref #153 
@mxmssh @ZetaTwo

refactor: Crawler/sql instances

---

src/gcp_scanner/crawl.py
src/gcp_scanner/crawler/bigquery_crawler.py
src/gcp_scanner/crawler/crawler_factory.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py

closes #206 
ref to #153 
@mshudrak @ZetaTwo

refactor: Crawler/bq

---

src/gcp_scanner/crawl.py
src/gcp_scanner/crawler/crawler_factory.py
src/gcp_scanner/crawler/kms_keys_crawler.py
src/gcp_scanner/scanner.py
src/gcp_scanner/test_unit.py

**closes**
closes #210 
ref to #153 
@mshudrak @ZetaTwo

refactor: Crawler/kms keys

---

src/gcp_scanner/client/client_factory.py
src/gcp_scanner/client/cloud_resource_manager_client.py
src/gcp_scanner/test_unit.py

:art: updated filename and classname to match with the resource name.

---

visualization_tool/src/components/ResourcesList/ResourcesList.css
visualization_tool/src/components/ResourcesList/ResourcesList.tsx
visualization_tool/src/components/ResourcesList/partials/Detalis.tsx
visualization_tool/src/types/resources.ts

Add a details drawer to show most of the information about the resource

feat: Add Details Drawer to Resources Cards

---

src/gcp_scanner/models.py
src/gcp_scanner/scanner.py

- Parallelized GCP resource computation using the `ThreadPoolExecutor()`.
- Improves tool runtime from ~37s to ~12s.
@mshudrak @ZetaTwo

feat✨: add resource parallelization

---

visualization_tool/package-lock.json
visualization_tool/src/components/ControlMenu/Controller.ts
visualization_tool/src/components/ControlMenu/partials/UploadMenu.tsx
visualization_tool/src/types/resources.ts

Edit parser to handle new output file format introduced in #284 PR

fix: Handle new output file format

---

visualization_tool/src/components/ControlMenu/Controller.ts
visualization_tool/src/components/ControlMenu/partials/UploadMenu.tsx
visualization_tool/src/parser/parser.ts
visualization_tool/src/types/resources.ts

Provide a more easier flow for adding multiple files to the visualizer 
- Separate parsing logic from `Controller.ts` to `parser/parser.ts`
- Refactor `UploadMenu` component
#277 #279
The Usage guide needs to be updated but I will delay it as the next PR will add changes to the UI

feat: Easier flow for uploading files to the visualizer

---

README.md

The PR contains a minor grammar suggestion.

Grammer and typos fix suggestion

---

src/gcp_scanner/credsdb.py

Very minor nitpick fix.
Removes extra dot(.) in comment

Remove extra dot

---

README.md

This PR adds missing language fences to the `README.md` file

chore: add missing lang fences
